### ISSUE TITLE
Usage output is formatted wrongly

### ISSUE THREAD

**Issue by KristobalJunta** [75lb/renamer#20] opened 2016-04-13 01:55 UTC
As already mentioned as off-topic in #18, the usage output is formatted wrongly
This is a 1366x768 screen of gnome-terminal:  
![screenshot from 2016-04-13 04-50-52](https://cloud.githubusercontent.com/assets/6359247/14480668/d2250bd6-0133-11e6-9194-4ff9a3615c35.png)

**Comment by 75lb** [comment] 2016-04-13 07:07
will take a look today, thanks.

**Comment by KristobalJunta** [comment] 2016-04-13 08:59
I am also planning to take a look at that and maybe do a pull request, but
dunno if I would have spare time soon.

**Comment by 75lb** [comment] 2016-04-13 09:17
thanks, but don't worry - looking at it now.

**Comment by 75lb** [comment] 2016-04-13 11:35
i'm unable to reproduce this.. i'm in gnome-terminal on Ubuntu 15 with the default font.. node v5, renamer v0.5.6.. 

![screen shot 2016-04-13 at 12 30 58](https://cloud.githubusercontent.com/assets/1247980/14491921/a607fa14-0173-11e6-8bd4-df6031a3ef1f.png)

**Comment by 75lb** [comment] 2016-04-13 11:58
what value is your `TERM` environment variable set to? this is mine:
```
$ echo $TERM
xterm-256color
```

**Comment by KristobalJunta** [comment] 2016-04-13 18:37
It's OpenSuse Tumbleweed, Gnome 3.20. Font is Droid Sans Mono, but I dont think it affects the output in that way.
```
echo $TERM
xterm-256color
```

**Comment by 75lb** [comment] 2016-04-13 21:10
fixed by upgrading dependent modules to latest versions.. released in renamer v0.5.7.. thanks again for the report 👍 

@tandrewnichols @ismyrnow

**Closed by 75lb** 2016-04-13 21:10 UTC
Labels: bug

**Comment by KristobalJunta** [comment] 2016-04-13 23:36
Weeeell, I'm still here with the bug
Somehow, when I run renamer with `node bin/cli.js -h` everything is well (even the older 0.5.6 version)
But, using the `renamer` command it all stays the same. I updated it to v0.5.7 just now.

**Comment by 75lb** [comment] 2016-04-13 23:41
Do you have two versions installed,one globally, one local? On your local
checkout make sure the npm modules are updated

**Comment by KristobalJunta** [comment] 2016-04-13 23:42
First case, I run source code checked out from github, the second - installed via npm

**Comment by KristobalJunta** [comment] 2016-04-13 23:44
Whoa. I dunno what happened, I just reinstalled renamer via npm and all works
It defenitely was v0.5.7 before reinstallation, I double-checked, but... pure magic :)
