### ISSUE TITLE
--git flag?

### ISSUE THREAD

**Issue by codfish** [75lb/renamer#62] opened 2022-08-24 19:47 UTC
Thoughts on providing a `--git` flag (name WIP) to the cli that would run `git` instead of `fs` [here](https://github.com/75lb/renamer/blob/83e33852c58f9f34d3f7ae32d0e216270f3bd498/lib/rename-file.js#L28)? Would need to solve for elegantly running a git command in node but would be helpful.

**Scenario**: I have to rename a ton of files in a git repo but i need to use `git mv` so i don't lose history.

I would be open to building this, just wanted to get initial thoughts and if it sounds like something you would like to add, any suggestions/requirements come to mind?

**Comment by 75lb** [comment] 2023-01-16 16:06
Marking this is a dupe of #58. Yes, we need this feature.. Suggestions welcome as to how you would like/expect it to be solved..

**Closed** 2023-01-16 16:06 UTC
Labels: enhancement
